spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/db_web?useUnicode=true&characterEncoding=UTF8&useSSL=false&
    username: root
    password: yuan
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.yuan.spring.boot.exam.demo.model
#logging:
#  level:
#    cn.yuan.spring.boot.exam.demo.mapper: debug
